import { NextResponse } from "next/server";

/**
 * Slack send endpoint for the Reports flow. Stubbed — returns a 412 with
 * setup instructions until the user wires their Slack app.
 *
 * To activate (3 steps):
 *   1. Create a Slack app at https://api.slack.com/apps?new_app=1
 *      Bot token scopes: `files:write` (image upload),
 *      `chat:write` (post messages), `chat:write.public` (post anywhere).
 *      Install to workspace → copy the Bot User OAuth Token.
 *   2. Find your Slack member ID (Profile → ⋮ → Copy member ID).
 *      Or to post to a channel, copy the channel ID from its URL.
 *   3. Set on Vercel:
 *        SLACK_BOT_TOKEN=xoxb-...
 *        SLACK_REVIEW_CHANNEL=Uxxxxxxxx   (member ID for DM, or Cxxxxxxxx for channel)
 *
 * The "approval" UX is by convention: messages land in the user's DM with
 * the bot first; the user verifies the image / wording, then forwards to
 * the team channel manually. This is simpler than building Slack
 * Workflow Builder buttons and works without any extra Slack scopes.
 */

interface SlackPayload {
  template: string;
  title: string;
  imageDataUrl: string;
}

export async function POST(req: Request) {
  const token = process.env.SLACK_BOT_TOKEN;
  const channel = process.env.SLACK_REVIEW_CHANNEL;
  if (!token || !channel) {
    return NextResponse.json(
      {
        ok: false,
        message: "Slack not configured.",
        setupHint:
          "To enable: create a Slack app with files:write + chat:write scopes, install it to your workspace, then set SLACK_BOT_TOKEN and SLACK_REVIEW_CHANNEL on Vercel. Until then, use Download PNG / PDF and paste manually.",
      },
      { status: 412 },
    );
  }

  let body: SlackPayload;
  try {
    body = (await req.json()) as SlackPayload;
  } catch {
    return NextResponse.json(
      { ok: false, message: "Bad request — invalid JSON." },
      { status: 400 },
    );
  }
  if (!body.imageDataUrl?.startsWith("data:image/")) {
    return NextResponse.json(
      { ok: false, message: "Bad request — imageDataUrl is required." },
      { status: 400 },
    );
  }

  // data:image/png;base64,iVBOR... → base64-decoded buffer.
  const commaIdx = body.imageDataUrl.indexOf(",");
  const b64 = body.imageDataUrl.slice(commaIdx + 1);
  const buffer = Buffer.from(b64, "base64");
  const filename = sanitizeFilename(body.title) + ".png";

  // Upload via Slack's modern files API (files.getUploadURLExternal +
  // files.completeUploadExternal). The legacy files.upload was deprecated
  // in 2024 and is being removed.
  try {
    const upload = await getUploadUrl(token, filename, buffer.byteLength);
    if (!upload.ok) {
      return NextResponse.json(
        {
          ok: false,
          message: `Slack: ${upload.error ?? "could not get upload URL"}`,
        },
        { status: 502 },
      );
    }
    await uploadToSlack(upload.upload_url, buffer);
    const complete = await completeUpload(
      token,
      upload.file_id,
      filename,
      channel,
      `${body.title} · auto-generated by JBP Dashboard`,
    );
    if (!complete.ok) {
      return NextResponse.json(
        {
          ok: false,
          message: `Slack: ${complete.error ?? "could not complete upload"}`,
        },
        { status: 502 },
      );
    }
    return NextResponse.json({
      ok: true,
      message:
        "Sent to Slack — review the image in your DM, then forward to the team channel.",
    });
  } catch (err) {
    return NextResponse.json(
      {
        ok: false,
        message:
          err instanceof Error ? err.message : "Slack send failed",
      },
      { status: 502 },
    );
  }
}

interface UploadUrlResponse {
  ok: boolean;
  upload_url: string;
  file_id: string;
  error?: string;
}

async function getUploadUrl(
  token: string,
  filename: string,
  bytes: number,
): Promise<UploadUrlResponse> {
  const url = new URL("https://slack.com/api/files.getUploadURLExternal");
  url.searchParams.set("filename", filename);
  url.searchParams.set("length", String(bytes));
  const res = await fetch(url.toString(), {
    headers: { Authorization: `Bearer ${token}` },
  });
  return (await res.json()) as UploadUrlResponse;
}

async function uploadToSlack(uploadUrl: string, buffer: Buffer): Promise<void> {
  const res = await fetch(uploadUrl, {
    method: "POST",
    body: new Uint8Array(buffer),
    headers: { "Content-Type": "application/octet-stream" },
  });
  if (!res.ok) {
    throw new Error(`Slack upload returned ${res.status}`);
  }
}

interface CompleteUploadResponse {
  ok: boolean;
  error?: string;
}

async function completeUpload(
  token: string,
  fileId: string,
  filename: string,
  channel: string,
  initialComment: string,
): Promise<CompleteUploadResponse> {
  const res = await fetch(
    "https://slack.com/api/files.completeUploadExternal",
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json; charset=utf-8",
      },
      body: JSON.stringify({
        files: [{ id: fileId, title: filename }],
        channel_id: channel,
        initial_comment: initialComment,
      }),
    },
  );
  return (await res.json()) as CompleteUploadResponse;
}

function sanitizeFilename(s: string): string {
  return s.replace(/[^A-Za-z0-9-_]+/g, "-").replace(/^-+|-+$/g, "") || "report";
}
