import { NextResponse } from "next/server";

/**
 * Slack send endpoint for the Reports flow. Posts the rendered report PNG
 * to a Slack destination — either a channel ID (`C…` / `G…`) or a user
 * ID (`U…`), in which case we open the DM first.
 *
 * Required Vercel env vars:
 *   SLACK_BOT_TOKEN=xoxb-…
 *   SLACK_REVIEW_CHANNEL=Uxxxxxxxx   (member ID for DM, or Cxxxxxxxx for channel)
 *
 * Required Slack bot scopes:
 *   files:write          (upload the image)
 *   chat:write           (post the file message)
 *   im:write             (only when SLACK_REVIEW_CHANNEL is a user ID — open DM)
 *   chat:write.public    (only when posting to channels the bot isn't in)
 *
 * After changing scopes you must reinstall the app to mint a fresh token.
 */

interface SlackPayload {
  template: string;
  title: string;
  imageDataUrl: string;
}

export async function POST(req: Request) {
  const token = process.env.SLACK_BOT_TOKEN;
  const destination = process.env.SLACK_REVIEW_CHANNEL;
  if (!token || !destination) {
    return NextResponse.json(
      {
        ok: false,
        message: "Slack not configured.",
        setupHint:
          "Set SLACK_BOT_TOKEN and SLACK_REVIEW_CHANNEL on Vercel (Project → Settings → Environment Variables) and redeploy. Required scopes on the Slack bot: files:write + chat:write (+ im:write when the destination is a user ID).",
      },
      { status: 412 },
    );
  }

  let body: SlackPayload;
  try {
    body = (await req.json()) as SlackPayload;
  } catch {
    return NextResponse.json(
      { ok: false, message: "Bad request — invalid JSON." },
      { status: 400 },
    );
  }
  if (!body.imageDataUrl?.startsWith("data:image/")) {
    return NextResponse.json(
      { ok: false, message: "Bad request — imageDataUrl is required." },
      { status: 400 },
    );
  }

  const commaIdx = body.imageDataUrl.indexOf(",");
  const b64 = body.imageDataUrl.slice(commaIdx + 1);
  const buffer = Buffer.from(b64, "base64");
  const filename = sanitizeFilename(body.title) + ".png";

  try {
    // 1. Resolve a real channel ID. If the destination is a user ID
    //    (`U…`), open a DM with that user — Slack returns a `D…` channel
    //    ID we can post the file to. Channel IDs (`C…` / `G…` / `D…`)
    //    pass through unchanged.
    const channelId = await resolveChannel(token, destination);

    // 2. Ask Slack for an upload URL.
    const upload = await getUploadUrl(token, filename, buffer.byteLength);
    if (!upload.ok) {
      return NextResponse.json(
        {
          ok: false,
          message: `Slack files.getUploadURLExternal: ${upload.error ?? "unknown error"}`,
          slackError: upload.error,
          step: "getUploadURLExternal",
        },
        { status: 502 },
      );
    }

    // 3. PUT/POST the bytes to the upload URL.
    await uploadToSlack(upload.upload_url, buffer);

    // 4. Tell Slack the upload is done — and which channel to share into.
    const complete = await completeUpload(
      token,
      upload.file_id,
      filename,
      channelId,
      `${body.title} · auto-generated by JBP Dashboard`,
    );
    if (!complete.ok) {
      return NextResponse.json(
        {
          ok: false,
          message: `Slack files.completeUploadExternal: ${complete.error ?? "unknown error"}`,
          slackError: complete.error,
          step: "completeUploadExternal",
        },
        { status: 502 },
      );
    }

    return NextResponse.json({
      ok: true,
      message: "Sent to Slack — check your DM.",
    });
  } catch (err) {
    return NextResponse.json(
      {
        ok: false,
        message: err instanceof Error ? err.message : "Slack send failed",
      },
      { status: 502 },
    );
  }
}

/* ──────────────── Slack API helpers ──────────────── */

async function resolveChannel(
  token: string,
  destination: string,
): Promise<string> {
  // Channel IDs start with C (public), G (private), D (DM). User IDs
  // start with U (or W for enterprise grid). We only need the DM-open
  // round-trip when the user passed a user ID.
  if (!destination.startsWith("U") && !destination.startsWith("W")) {
    return destination;
  }
  const res = await fetch("https://slack.com/api/conversations.open", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json; charset=utf-8",
    },
    body: JSON.stringify({ users: destination }),
  });
  const json = (await res.json()) as {
    ok: boolean;
    channel?: { id: string };
    error?: string;
  };
  if (!json.ok || !json.channel?.id) {
    throw new Error(
      `Slack conversations.open: ${json.error ?? "no channel returned"}` +
        (json.error === "missing_scope"
          ? " (the bot needs the im:write scope; reinstall the app after adding it)"
          : ""),
    );
  }
  return json.channel.id;
}

interface UploadUrlResponse {
  ok: boolean;
  upload_url: string;
  file_id: string;
  error?: string;
}

async function getUploadUrl(
  token: string,
  filename: string,
  bytes: number,
): Promise<UploadUrlResponse> {
  // Slack accepts both GET and POST here, but POST + form-encoded is the
  // documented happy path and is what slack-sdk uses internally.
  const params = new URLSearchParams();
  params.set("filename", filename);
  params.set("length", String(bytes));
  const res = await fetch(
    "https://slack.com/api/files.getUploadURLExternal",
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
      },
      body: params.toString(),
    },
  );
  return (await res.json()) as UploadUrlResponse;
}

async function uploadToSlack(
  uploadUrl: string,
  buffer: Buffer,
): Promise<void> {
  const res = await fetch(uploadUrl, {
    method: "POST",
    body: new Uint8Array(buffer),
    headers: { "Content-Type": "application/octet-stream" },
  });
  if (!res.ok) {
    throw new Error(`Slack upload returned ${res.status}`);
  }
}

interface CompleteUploadResponse {
  ok: boolean;
  error?: string;
}

async function completeUpload(
  token: string,
  fileId: string,
  filename: string,
  channelId: string,
  initialComment: string,
): Promise<CompleteUploadResponse> {
  const res = await fetch(
    "https://slack.com/api/files.completeUploadExternal",
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json; charset=utf-8",
      },
      body: JSON.stringify({
        files: [{ id: fileId, title: filename }],
        channel_id: channelId,
        initial_comment: initialComment,
      }),
    },
  );
  return (await res.json()) as CompleteUploadResponse;
}

function sanitizeFilename(s: string): string {
  return (
    s.replace(/[^A-Za-z0-9-_]+/g, "-").replace(/^-+|-+$/g, "") || "report"
  );
}
