import { NextResponse } from "next/server";
import {
  completeUpload,
  getUploadUrl,
  resolveChannel,
  sanitizeFilename,
  uploadBytesToSlack,
} from "@/lib/slack";

/**
 * Slack send endpoint for the manual "Send via Slack" button. Posts the
 * rendered report PNG to either the per-template destination (passed in the
 * request body) or the SLACK_REVIEW_CHANNEL env var fallback.
 *
 * See lib/slack.ts for required scopes.
 */

interface SlackPayload {
  template: string;
  title: string;
  imageDataUrl: string;
  /** Optional override — channel ID, DM ID, or user ID. */
  destination?: string;
}

const dateFormatter = new Intl.DateTimeFormat("en-US", {
  timeZone: "America/Chicago",
  weekday: "short",
  month: "short",
  day: "numeric",
  year: "numeric",
});

export async function POST(req: Request) {
  const token = process.env.SLACK_BOT_TOKEN;
  if (!token) {
    return NextResponse.json(
      {
        ok: false,
        message: "Slack not configured.",
        setupHint:
          "Set SLACK_BOT_TOKEN on Vercel (Project → Settings → Environment Variables) and redeploy. Required scopes: files:write + chat:write (+ im:write when the destination is a user ID).",
      },
      { status: 412 },
    );
  }

  let body: SlackPayload;
  try {
    body = (await req.json()) as SlackPayload;
  } catch {
    return NextResponse.json(
      { ok: false, message: "Bad request — invalid JSON." },
      { status: 400 },
    );
  }
  if (!body.imageDataUrl?.startsWith("data:image/")) {
    return NextResponse.json(
      { ok: false, message: "Bad request — imageDataUrl is required." },
      { status: 400 },
    );
  }

  const destination =
    body.destination?.trim() || process.env.SLACK_REVIEW_CHANNEL;
  if (!destination) {
    return NextResponse.json(
      {
        ok: false,
        message:
          "No Slack destination — set SLACK_REVIEW_CHANNEL on Vercel or fill the customizer's Slack destination field.",
      },
      { status: 412 },
    );
  }

  const commaIdx = body.imageDataUrl.indexOf(",");
  const b64 = body.imageDataUrl.slice(commaIdx + 1);
  const buffer = Buffer.from(b64, "base64");
  const filename = sanitizeFilename(body.title) + ".png";
  const dateLabel = dateFormatter.format(new Date());

  try {
    const channelId = await resolveChannel(token, destination);
    const upload = await getUploadUrl(token, filename, buffer.byteLength);
    if (!upload.ok) {
      return NextResponse.json(
        {
          ok: false,
          message: `Slack files.getUploadURLExternal: ${upload.error ?? "unknown error"}`,
          slackError: upload.error,
          step: "getUploadURLExternal",
        },
        { status: 502 },
      );
    }
    await uploadBytesToSlack(upload.upload_url, buffer);
    const complete = await completeUpload(
      token,
      upload.file_id,
      filename,
      channelId,
      `*${body.title}* · ${dateLabel} CT · auto-generated by JBP Dashboard`,
    );
    if (!complete.ok) {
      return NextResponse.json(
        {
          ok: false,
          message: `Slack files.completeUploadExternal: ${complete.error ?? "unknown error"}`,
          slackError: complete.error,
          step: "completeUploadExternal",
        },
        { status: 502 },
      );
    }
    return NextResponse.json({
      ok: true,
      message: "Sent to Slack.",
    });
  } catch (err) {
    return NextResponse.json(
      {
        ok: false,
        message: err instanceof Error ? err.message : "Slack send failed",
      },
      { status: 502 },
    );
  }
}
